config/routes.rb
Rails.application.routes.draw do

  root 'searches#new'

  resources :searches
  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations, only: [:show, :new, :create, :destroy]
  end

  resources :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant



  # def self.reduce_capacity_when_reserved(restaurant_capacity, restaurant_id)
  #
  #   restaurant_capacity -=
  #   # restaurant_place_holder = Restaurant.find(restaurant_id)
  #   # reservation_place_holder = @reservation.people
  #   #
  #   #     if restaurant_place_holder.capacity - reservation_place_holder > 0
  #   #       restaurant_place_holder.capacity -= reservation_place_holder.people
  #   #       restaurant_place_holder.save
  #   #     end
  #
  #
  # end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :address, :city, :capacity, :open_hour, :close_hour, presence: true

  has_many :users, through: :reservations
  has_many :reservations
  belongs_to :user
  has_many :searches

  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end


end

app/models/search.rb
class Search < ActiveRecord::Base

  # Control on date for past date
  validate :not_past_date

  def not_past_date
    if self.time < Date.today
      errors.add(:time, 'not in past')
    end
  end

  def search_restaurants

    restaurants = Restaurant.all

    restaurants = restaurants.where(["capacity >= ?", people]) if people.present?
    restaurants = restaurants.where(["category LIKE ?", category]) if category.present?
    restaurants = restaurants.where(["price >= ?", min_price]) if min_price.present?
    restaurants = restaurants.where(["price <= ?", max_price]) if max_price.present?
    restaurants = restaurants.where(["city LIKE ?", location]) if location.present?

    return restaurants

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  validates :email, presence: true
  validates_uniqueness_of :username, :email

  has_many :restaurants, through: :reservations
  has_many :reservations
  has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

   def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end
 
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :ensure_logged_in, only: [:create, :destroy]

  def index
    @reservations = Reservation.all
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new
    @search = Search.last
  end

  def create
    @reservation = Reservation.new(reservation_params)
    u = Restaurant.find(params[:restaurant_id])
    @reservation.restaurant = u
    @reservation.user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.capacity -= @reservation.people
    @restaurant.save
    if @reservation.save

      restaurant_capacity = @restaurant.capacity
      restaurant_id = @restaurant.id

      # Reservation.reduce_capacity_when_reserved(restaurant_capacity, restaurant_id)

      redirect_to restaurant_path(@restaurant)

    else
      render :new
    end
  end

  def show
    @reservations = Reservation.find(params[:id])
  end

  def edit
    @reservations = Reservation.find(params[:id])
  end

  def update
    @reservations = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
      redirect_to reservation_url(@reservation)
    else
      render :edit
    end
  end

  def destroy
    @reservations = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_url
  end

  private
  def reservation_params
<<<<<<< HEAD
    params.require(:reservation).permit(:time, :people, :availability)
=======
    params.require(:reservation).permit(:time, :people, :hour)
>>>>>>> 3a1e8ce43b6b07b9c6b6d40a4c0f379bd1d194b8
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
    @reservation = Reservation.new

  end

  def show
    @restaurant = Search.find(params[:restaurant_id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create

    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_url(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_url(@restaurant)
    else
      render :edit
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :price, :capacity, :address, :city)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    categories
  end

  def create
    @search = Search.new(search_params)
    # binding.pry
    if @search.save
      redirect_to @search
    else
      categories
      render :new
    end
  end

  def show
    @search = Search.find(params[:id])
  end


  private

  def search_params
    params.require(:search).permit(:category, :min_price, :max_price, :people, :time, :hour, :location)
  end

  def categories
    @categories = Restaurant.uniq.pluck(:category)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # skip_before_action :require_login
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in!"
      redirect_to restaurants_path
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_path, notice: "Sign in!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to restaurant_url
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :username, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
    <div class="dropdown">
      <%= form_for @reservation do |f| %>
      <%= f.select(:people, Home::CLASS_PEOPLE) %>
      <%= f.date_field :time %>
      <%= f.select(:people, Home::CLASS_HOUR) %>
      <%= f.text_field :people %>
      <%= f.submit "Search" %>
      <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= csrf_meta_tags %>
</head>
  <body>
    <!-- Message error -->
    <div class="flash-message">
      <% if flash[:notice] %>
        <!-- Add Bootstrap CSS message alert -->
          <p id="notice"> <div class="alert alert-success" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
       <li><%= flash[:notice] %></li>
      </div>
      <% end %>
      <% if flash[:alert] %>
          <p id="alert">
            <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
         <li><%= flash[:alert] %></li>
        </div>
      <% end %>
    </div>
    <header class="center">
      <!-- Link log in - log out - User's profile -->
      <p class="userinfo">
        <% if current_user %>
        Signed in as <%= link_to current_user.username, user_path(current_user.id) %>.
        <%= link_to "Log out", new_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p>
    </header>
  <%= yield %>

  </body>

</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation)  do |f| %>

  <div class="field">
    <%= f.label :time %>
    <%= f.number_field :time %>
  </div>

  <div class="field">
    <%= f.label :people %>
    <%= f.number_field :people %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :restaurant_id %>
    <%= f.number_field :restaurant_id %>
  </div>

  <div class="field">
    <%= f.label :availability %>
    <%= f.number_field :availability %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% if @reservation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved. </h2>

    <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1><%= @reservation %></h1>
<%= render 'form' %>
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Master Reservations list</h1>

<%= @reservations.each do |x| %>
  <p>
    Time:
    <%= x.time %><br>

    People:
    <%= x.people %><br>

    User id:
    <%= x.user_id %><br>

    Restaurant id:
    <%= x.restaurant_id %><br>

    Availability:
    <%= x.availability %><br>
    <%= link_to 'Show', reservation_path(x) %> | <%= link_to 'Edit', edit_reservation_path(x) %> | <%= link_to 'Delete', x, method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
  </p>
<% end %>

app/views/reservations/new.html.erb
<h1>Add a Reservation</h1>

<p>
  Hi <%= current_user.username %>!!! <br>
  Please confirm your reservation at <%= @restaurant.name %>.
</p>

People: <%= @search.people %><br />
Time: <%= @search.time %>
Hour: <%= @search.hour %>

<%= form_for [@restaurant, @reservation]  do |f| %>


<%= f.hidden_field :people, :value => @search.people %>
<%= f.hidden_field :time, :value => @search.time %>
<%= f.hidden_field :hour, :value => @search.hour %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<% if @reservation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved. </h2>

    <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/reservations/show.html.erb
<h1>Your Reservation</h1>
<p>
  Time:
  <%= @reservation.time %><br>
  People:
  <%= @reservation.people %><br>
  User name:
  <%= @reservation.user.username %><br>
  Restaurant name:
  <%= @reservation.restaurant.name %><br>
  Availability:
  <%= @reservation.availability %><br>
</p>

<%= link_to 'Back', reservations_path %> | <%= link_to 'Edit', edit_reservation_path(@reservation) %> 

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :price%>
    <%= f.number_field :price%>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="field">
    <%= f.label :open_hour %>
    <%= f.number_field :open_hour %>
  </div>

  <div class="field">
    <%= f.label :close_hour %>
    <%= f.number_field :close_hour %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to "Back to Restaurants", restaurants_path %>


<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved</h2>

    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/delete.html.erb
<h1>Restaurants#delete</h1>
<p>Find me in app/views/restaurants/delete.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="center">

<%= link_to 'New Search', new_search_path %>

  <h1>List of Restaurants</h1><br><br>

<% @restaurants.each do |rest|  %>

  <p>
    <b>Name:</b> <%= link_to rest.name, restaurant_path(rest) %> <br>
    <b>Category:</b> <%= rest.category %> <br>
    <b>Price Range:</b> <%= rest.price %> <br>
    <b>Capacity:</b> <%= rest.capacity %><br>
    <b>ID Num of DB</b> <%= rest.id %><br>
    <b>Location:</b><%= rest.city %><br>
  </p>
    <%= link_to 'Show', restaurant_path(rest) %> | <%= link_to 'Edit', edit_restaurant_path(rest) %> | <%= link_to 'Delete', rest, method: :delete, data: {confirm: "Are you sure about that?!?!"} %><br><br><br>
<% end %>

</div>

app/views/restaurants/new.html.erb
<h1>Add Your Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p>
  Category: <%= @restaurant.category %><br>
  Capacity: <%= @restaurant.capacity %><br>
  Price: <%= @restaurant.price %><br>
  Location: <%= @restaurant.city %><br>
</p>

<%= link_to 'Make a Reservation Here', new_restaurant_reservation_path(@restaurant) %>

<h3>Our Reservations List:</h3>

<table>
    <tr>
      <th><b>Date and Time</b></th>
      <th><b>Guests</b></th>
      <th><b>Customer</b></th>
    </tr>
  <% @restaurant.reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.time %></td>
      <td><%= reservation.people %></td>
      <td><%= reservation.user.username %></td>
    <tr>
  <% end %>
</table>

<%= link_to 'Back to Restaurants', restaurants_path %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/searches/new.html.erb
<div class="center background-home">
  <div class="content-center">
<div class="logo">
<!-- Insert the logo png -->
</div>

  <h1 class="words">Find a Table</h1>
  <%= form_for @search do |s| %>

    <div class="field">
      <p class="words"><%= s.label :time %></p>
      <p><%= s.date_field :time %></p>
    </div>

    <div class="field">
      <p class="words"><%= s.label :hour %></p>
      <p><%= s.select :hour, 4..11 %></p>
    </div>

    <div class="field">
      <p class="words"><%= s.label :people %></p>
      <p><%= s.text_field :people %></p>
    </div>

    <div class="field">
      <p class="words"><%= s.label :category %></p>
      <p><%= s.select :category, options_for_select(@categories), :include_blank => true %></p>
    </div>

    <div class="field">
      <p class="words"><%= s.label :min_price, "Min Price" %></p>
      <p><%= s.number_field :min_price %></p>
      <p class="words"><%= s.label :max_price, "Max Price" %></p>
      <p><%= s.number_field :max_price %></p>
    </div>

    <div class="field">
      <p class="words"><%= s.label :location %></p>
      <p><%= s.text_field :location %></p>
    </div>

    <div class="actions">
      <p><%= s.submit "Search"%></p>
    </div>

    <% end %>
    <p id="backbutton"><%= link_to "See All Restaurants", restaurants_path %></p>

    </div>
</div>

app/views/searches/show.html.erb
<div class="center">
  <h1>Search results:</h1>

  <p><%= link_to "Back", new_search_path%></p>
  <h3>Available Tables for <%= @search.people %> in <%= @search.time %>.</h3>

  <% if @search.search_restaurants.empty? %>
    <p>No Record Founded! </p>
  <% else %>
    <% @search.search_restaurants.each do |c| %>
      <br />
      <div class="field">
        <p>Name: <%= c.name %></p>
        <p>Category: <%= c.category %></p>
        <p>Price: <%= c.price %></p>
        <p>Capacity: <%= c.capacity %></p>
        <p>Location: <%= c.city %></p>
        <%= link_to 'Make a Reservation Here', new_restaurant_reservation_path(c, search_id: @search) %>
      </div>
      <% end %>
  <% end %>
</div>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="center">
<h1>Sign up</h1>

  <%= form_for @user do |u| %>
  <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Error:</span>
       <li><%= message %></li>
      </div>
            <% end %>
          </ul>
        </div>
      <% end %>
    <div class="field">
      <%= u.label :username %> <br>
      <%= u.text_field :username %> <br>
    </div>
    <div class="field">
      <%= u.label :email %><br>
      <%= u.text_field :email %> <br>
    </div>
    <div class="field">
      <%= u.label :phone %><br>
      <%= u.text_field :phone %> <br>
    </div>
    <div class="field">
      <%= u.label :password %><br>
      <%= u.text_field :password %> <br>
    </div>
    <div class="field">
      <%= u.label :password_confirmation %><br>
      <%= u.text_field :password_confirmation %> <br>
    </div>
    <div class="actions">
      <%= u.submit "Save"%><br>
    </div>
    </div>
<% end %>

app/views/users/show.html.erb
<div class="center">
<h1>My Profile</h1>

  <p>
    <b>Name:</b>  <%= current_user.username %> <br>
    <b>Email:</b>  <%= current_user.email %> <br>
    <b>Phone:</b>  <%= current_user.phone %> <br>
  </p>

  <%= link_to "Back to Restaurants", restaurant_url %> | <%= link_to "Add a New Restaurant", new_restaurant_url %>

<h2>My Reservations</h2>

<table>
    <tr>
      <th><b>Date and Time</b></th>
      <th><b>Guests</b></th>
      <th><b>Customer</b></th>
    </tr>
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.time %> </td>
      <td><%= reservation.people %></td>
      <td><%= reservation.restaurant_id %></td>
    <tr>
  <% end %>
</table>


<h2>My Restaurants:</h2>
  <% @restaurants.each do |list| %>
    <% if @current_user.user_id == restaurant.user.user_id %>
    <%= current_user.restaurant.name %>
    <% end %>
  <% end %>

<h2>Reservations For Restaurant</h2>

  <% @users.restaurants.each do |restaurant| %>
    <% if current_user == restaurant.user_id %>
      <table>
        <tr>
          <th><b>Date and Time</b></th>
          <th><b>Guests</b></th>
          <th><b>Customer</b></th>
        </tr>

        <% @restaurant.reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.time %></td>
            <td><%= reservation.people %></td>
            <td><%= reservation.user.username %></td>
          <tr>
          <% end %>
    <% end %>
  <% end %>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>